name: Mirror to GitLab

# on:
#   schedule:
#     - cron: '*/30 * * * *'   # every 30 minutes
#   workflow_dispatch:

permissions:
  contents: read  # we only need to read from GitHub

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror GitHub → GitLab
        run: |
          git clone --mirror https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/angryolli/network-simulator.git repo.git
          cd repo.git
          git push --mirror https://oauth2:${{ secrets.GITLAB_TOKEN }}@version.aalto.fi/gitlab/bulgyno1/network-simulator.git
